
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATATYPE ID LBRACE LPAREN RBRACE RPAREN SEMICOLONstatement : declaration\n| function_declaration\n| function_definitiondeclaration : DATATYPE ID SEMICOLONfunction_declaration : DATATYPE ID LPAREN RPAREN SEMICOLONfunction_definition : DATATYPE ID LPAREN RPAREN LBRACE RBRACE'
    
_lr_action_items = {'DATATYPE':([0,],[5,]),'$end':([1,2,3,4,7,10,12,],[0,-1,-2,-3,-4,-5,-6,]),'ID':([5,],[6,]),'SEMICOLON':([6,9,],[7,10,]),'LPAREN':([6,],[8,]),'RPAREN':([8,],[9,]),'LBRACE':([9,],[11,]),'RBRACE':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'declaration':([0,],[2,]),'function_declaration':([0,],[3,]),'function_definition':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> declaration','statement',1,'p_statement','parser.py',8),
  ('statement -> function_declaration','statement',1,'p_statement','parser.py',9),
  ('statement -> function_definition','statement',1,'p_statement','parser.py',10),
  ('declaration -> DATATYPE ID SEMICOLON','declaration',3,'p_declaration','parser.py',14),
  ('function_declaration -> DATATYPE ID LPAREN RPAREN SEMICOLON','function_declaration',5,'p_function_declaration','parser.py',18),
  ('function_definition -> DATATYPE ID LPAREN RPAREN LBRACE RBRACE','function_definition',6,'p_function_definition','parser.py',22),
]
